archef_n_2/archef/urls.py
from django.urls import path
from archef import views



app_name = 'archef'


urlpatterns = [
    path('start_page/', views.start_page , name='start_page'),
    path('search/', views.search , name='search'),
    path('view/', views.view_results, name='view'),
    path('store/', views.store, name='store'),
    path('edit/<int:record_id>/', views.edit, name='edit'),
    path('edit_d/<int:decision_id>/', views.edit_d, name='edit_d'),
    path('edit_redirect/<int:decision_id>/', views.edit_redirect, name='edit_redirect'),
    path('delete/<int:record_id>/', views.delete, name='delete'),
]

archef_n_2/archef_n_2/urls.py
from django.contrib import admin
from django.urls import path,include
from archef import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.user_login, name='user_login'),
    path('archef/',include('archef.urls')),
    path('logout/',views.user_logout, name='log_out'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archef_n_2/archef/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

#import built in user model
from django.contrib.auth.models import User
#

## create our models
#first one is the part model




class Part(models.Model):
    name = models.CharField(max_length = 64)


    def __str__(self):
        return self.name




### second models
#2- user model

class ArchefUser(models.Model):
    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_main_id = models.IntegerField(primary_key = True , validators=[MinValueValidator(1)])
    part = models.ForeignKey(Part, on_delete=models.CASCADE)


    def __str__(self):
        return  "user name : " + self.user.username + " , part: "+ self.part.name





### 3- model  --  decision

import datetime
class Decision(models.Model):
    #id = models.AutoField(primary_key=True)
    dec_num = models.IntegerField( )
    dec_year = models.IntegerField( validators=[MaxValueValidator(2100), MinValueValidator(1900)])
    dec_date = models.DateField(default = datetime.date.today)
    # user that  creates and regisers the decision
    user = models.ForeignKey(ArchefUser, on_delete=models.SET_NULL, null= True)
    related_part = models.CharField(max_length=64, default="nozom")
    decision_file = models.FileField(upload_to='%Y/',  null =True  )
    #decision_file = models.FileField(upload_to='files/',  null =True  )

    def __str__(self):
        return "decision number: "+str(self.dec_num)  + " realted part is : "+ self.related_part




##4- model ---   decsion_record

class DecisionRecord(models.Model):
    id = models.AutoField(primary_key=True)
    year = models.IntegerField(validators=[MaxValueValidator(2100), MinValueValidator(1900)])
    markaz = models.IntegerField()
    mosalsal = models.IntegerField()
    name = models.CharField(max_length = 256)
    national_num = models.IntegerField(  validators=[MaxValueValidator(40000000000000), MinValueValidator(20000000000000)])
    #national_num = models.CharField(primary_key=True, max_length=14, validators=[RegexValidator(r'^\d{1,10}$')])
    change_type = models.CharField(max_length=128)
    #many to one relationship
    decision = models.ForeignKey(Decision, on_delete=models.CASCADE)


    def __str__(self):
        return "name: "+ self.name  + ", change_type : "+self.change_type +", (dec num, dec year) --->> ("+str(self.decision.dec_num) + ", "+ str(self.decision.dec_year) +")"





class Shab(models.Model):
    year = models.PositiveIntegerField()
    markaz = models.PositiveIntegerField()
    mosalsal = models.PositiveIntegerField()
    nat_id = models.PositiveIntegerField(null = True)
    name = models.CharField(max_length = 264, null = True)


    def __str__(self):
         return "name: "+ self.name + ", nat_id: "+ str(self.nat_id)

archef_n_2/archef/forms.py
from django import forms

archef_n_2/archef/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
# Create your views here.

#authentication functions
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth.decorators import login_required
from   datetime import datetime, date


# import our database tables
from archef import  models
# from typing import Final




#global user variable
#cur_logged_user = models.ArchefUser()

def user_login(request):
    failed=0
    context={}
    if request.method == 'POST':

        #get user data and authenticate him
        user_main_id = request.POST['user_name']
        password = request.POST['user_password']
        #global cur_logged_user
        #cur_logged_user = models.ArchefUser.objects.filter(pk = user_main_id).first()
        cur_logged_user = models.ArchefUser.objects.filter(pk = user_main_id).first()
        #print( str(cur_logged_user))
        if cur_logged_user:
            user = authenticate( username= cur_logged_user.user.username, password = password)
        #print("user_id is: " + user_name)
        #print("user_id is: " + password)
        #print("user: " + str(user))
        # if a valid user loged in
            if user:
                if user.is_active:
                    login(request, user)
                    print("user {} is logged in the system at {}".format(request.user.username, str(datetime.now())))
                    return  HttpResponseRedirect(reverse('archef:start_page'))
                else:
                    print("user account is disabled")
            else:
                failed =1
        else:
           print("not authorized user is trying to log in the system")
           failed =1
        #    context = {'failed' : failed}
        #    return render(request, 'archef/user_login.html', context = context)

    context = {'failed' : failed}
    return render(request,'archef/user_login.html',  context = context)







@login_required
def start_page(request):
        return render(request,'archef/start_page.html')



@login_required
def edit(request, record_id):
        success = 0
        record = models.DecisionRecord.objects.filter(id = record_id).last()
        decision_id = models.Decision.objects.filter(id = record.decision.id).last().id

        if request.method == 'POST' and has_right_to_edit(request, decision_id):
            #print(decision)
            year = request.POST['year']
            markaz = request.POST['markaz']
            mosalsal = request.POST['mosalsal']
            name = request.POST['m_name']
            national_num= request.POST['national_num']
            change_type = request.POST['change_type']
            ### errors due to chabs change their old data by moving to other gorvernorants
            shab_old = models.Shab.objects.filter(year = year, markaz=markaz, mosalsal = mosalsal).first()
            shab_new = models.Shab(year = year,markaz = markaz, mosalsal = mosalsal, name =name, nat_id=national_num )
            #shab_new.save()
            if shab_old :
                    shab_old.delete()
                    shab_new.save()


            ## update record
            models.DecisionRecord.objects.filter(id = record_id).update(year = year,markaz= markaz,mosalsal= mosalsal, name = name,
                                            national_num= national_num, change_type= change_type )

            success = 1
            record = models.DecisionRecord.objects.filter(id = record_id).last()
            decision_id = models.Decision.objects.filter(id = record.decision.id).last().id
            url = 'archef:edit_redirect'
            # url = reverse(url)
            return redirect(url,decision_id)

        record = models.DecisionRecord.objects.filter(id = record_id).first()
        #print('Record data', str(record))
        context = {
            'record':record,
            'success':success,
        }
        return render(request,'archef/edit.html', context = context)



@login_required
def delete(request, record_id):

        record = models.DecisionRecord.objects.filter(id = record_id).last()
        decision = models.Decision.objects.filter(id = record.decision.id).last()

        cur_user = User.objects.filter(username = request.user.username).first()
        cur_user_id = models.ArchefUser.objects.filter(user = cur_user).first().user_main_id
        dec_user_id =decision.user.user_main_id

        if has_right_to_edit(request, decision.id):
            record.delete()


        url = 'archef:edit_redirect'
        # url = reverse(url)
        return redirect(url,decision.id)


def has_right_to_edit(request , decision_id):
        cur_user = User.objects.filter(username = request.user.username).first()
        cur_user_id = models.ArchefUser.objects.filter(user = cur_user).first().user_main_id
        dec_user_id =decision.user.user_main_id

        if dec_user_id == cur_user_id  or request.user.groups.filter(name = 'Administrators').exists():
            return True
        else:
            return False

@login_required
def edit_d(request, decision_id):
        success = 0
        if request.method == 'POST' and has_right_to_edit(request, decision_id):
            decision_num = int(request.POST['decision_num'])
            decision_year = request.POST['decision_year']

            if 'decision_date' in request.POST and request.POST['decision_date'] != '' :
                decision_date = request.POST['decision_date']
            else:
                decision_date = models.Decision.objects.filter(id = decision_id).first().dec_date

            part = request.POST['part']

            if 'url' in request.FILES:
                    file = request.FILES['url']
                    file = '/'+str( datetime.now().year)+'/'+str(file)
            else :
                file = models.Decision.objects.filter(id = decision_id).first().decision_file


            models.Decision.objects.filter(id = decision_id).update(dec_num= decision_num, dec_year = decision_year,dec_date= decision_date,related_part= part,decision_file = file )
            success=1
            url = 'archef:edit_redirect'
            # url = reverse(url)
            return redirect(url,decision_id)
            #return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            # decision =models.Decision.objects.filter(id = decision_id).last()
            # records = models.DecisionRecord.objects.filter(decision =decision ).reverse()
            #
            # context = {'records':records , 'user_name':request.user.username , 'decision' :decision, 'not_searched':1, 'new_decision':models.Decision.objects.filter(dec_year = datetime.now().year).last().dec_num+1}
            # #return render(request,'archef/store.html', context )
            # return render(request,'archef/store.html',context= context)


        decision = models.Decision.objects.filter(id = decision_id).first()
        #print('Record data', str(record))
        context = {
            'decision':decision,
            'success':success,
        }
        return render(request,'archef/edit_d.html', context = context)


@login_required
def edit_redirect(request, decision_id):
    if request.method == "POST":
        return store(request)
        #return redirect('archef:store',request)
    decision =models.Decision.objects.filter(id = decision_id).last()
    records = models.DecisionRecord.objects.filter(decision =decision ).reverse()
    context = {'records':records , 'user_name':request.user.username , 'decision' :decision, 'not_searched':1, 'new_decision':models.Decision.objects.filter(dec_year = datetime.now().year).last().dec_num+1}
    #return render(request,'archef/store.html', context )
    return render(request,'archef/store.html',context= context)





@login_required
def search(request):
    if request.method == "POST":
        year = request.POST['year']
        markaz = request.POST['markaz']
        mosalsal = request.POST['mosalsal']
        #get all decisions for this number if found
        records = models.DecisionRecord.objects.filter(year=year, markaz=markaz, mosalsal = mosalsal)
        record = records.first()
        #get shab data even if it does not have any chane
        shab = models.Shab.objects.filter(year = year, markaz=markaz, mosalsal = mosalsal).first()
        if not shab and record:
            shab = models.Shab(year = year,markaz = markaz, mosalsal = mosalsal, name = record.name, nat_id=record.national_num )
            #update shab records data base table
            shab.save()
        #print(shab)
        # for record in records:
        #      print(record.decision.decision_file)
        return view_results(request, {'records':records, 'record':shab})
    else:
        return render(request,'archef/search.html')



@login_required
def view_results(request , data):
     return render(request,'archef/view.html', context = data)



@login_required
def user_logout(request):
    logout(request)
    #return to home page
    return HttpResponseRedirect(reverse('user_login'))

from datetime import datetime
decision = models.Decision()

@login_required
def store(request):

    #user = User.objects.get(username =request.user.username )
    #ar_user = models.ArchefUser.objects.filter(user =user ).first()


    # get or return data to/from user

    #print(request.user)
    if request.method =='POST':
        if 'decision_num_search' in request.POST:
            #print(type(request.POST['year_search']))
            #print(request.POST['year_search'])
            if request.POST['year_search'] =='':
               dec_year = datetime.now().year
            else :
                dec_year = request.POST['year_search']

            global decision
            decision =models.Decision.objects.filter(dec_num =request.POST['decision_num_search'] , dec_year = dec_year ).first()

archef_n_2/archef/templates/archef/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'archef/bootstrap-4.3.1-dist/css/bootstrap.min.css' %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'archef/style.css' %}">
    <link rel="stylesheet" href="{% static 'archef/new_style.css' %}">
    <script src="{% static 'archef/jquery-3.4.1.min.js' %}"></script>
  </head>
<body >

    <nav class="navbar navbar-dark" style="direction:rtl">
        <h4 style="direction:rtl" class="text-center text-light">
          هيئة التنظيم و الادارة 
           <br>إدارة التجنيد و التعبئة
           <br>منطقة تجنيد وتعبئة الزقازيق
            <br> فرع نظم المعلومات <br>
                                    منظومة أرشيف قرارت السيد مدير المنطقة <br>
                                   <p> <script> document.write(new Date().toLocaleString());  </script><p>
                                    </h4>

        <img  class="img_1" width="150px"  src="{%static 'images/flag.jpg' %}" style="border: 1px solid #ddd; border-radius:4px; padding:5px;">


    </nav>
     <div class=' row  mx-3'>
     {% if user.is_authenticated %}
            <a href={%  url 'log_out'%}><button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">تسجيل الخروج</button></a>
        {% endif %}
    </div>


    <div class="container">
        {% block body_block%}
        {%endblock%}
    </div>


 <script src="{% static 'archef/bootstrap-4.3.1-dist/js/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 <script src="{% static 'archef/login.js' %}"></script>
</body>
</html>

archef_n_2/archef/templates/archef/edit.html
<!DOCTYPE html>
{% extends "archef/base.html" %}
{% load static %}
<script src="{% static 'archef/store.js' %}"></script>


{% block body_block %}

  <div class="container jumbotron " style="direction:rtl">

    <form method="post" id="new_record_form" target="_self"  >
    {%csrf_token%}
        <div class="form-group">

            <div class="row mr-4" >
                <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold" > السنة </h3>
                <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold" > المركز </h3>
                <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold " > المسلسل</h3>
            </div>



            <div class="row mr-4 form-group" >
                <input type='number' class='col-2 form-control m-1 text-right'  name='year'  form ="new_record_form" value="{{record.year}}"  required  >
                <input type='number' class='col-2 form-control m-1 text-right' name='markaz' form ="new_record_form"   value="{{record.markaz}}"  required >
                <input type='number' class='col-2 form-control m-1 text-right'  name='mosalsal'form ="new_record_form"  value="{{record.mosalsal}}"  required>
                <!-- It will be added later -->
                <!-- <input type="submit"  name='submit_sub_form' value ="بحث"  class="  m-1 btn  bg-light   text-center font-weight-bold"  form="form_sub"> -->


            </div>
            <div class="row  mr-2 form-group" >
                <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold" > الإسم </h3>
                <input type='text' class=' col-6 form-control m-1 text-right'  name='m_name' id="m_name"  value="{{record.name}}" required >

            </div>

            <div class="row  mr-2 form-group" >
                <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold" > الرقم القومى </h3>
                <input type='number' class=' col-6 form-control m-1 text-right'  name='national_num' id="national_num"   value="{{record.national_num}}" required >
            </div>

            <div class="row mr-2 form-group ">

                    <h3 class=" col-sm-3 m-1 btn-lg  bg-light  disabled text-center font-weight-bold " > نوع التعديل</h3>

                    <!--  NO NO ,THis Will be a list for now after that it will be a text choosen manullay depend on user type -->

                    <div class="col-sm-6 form-control-lg  ml-4">
                        <select class="form-control" name="change_type" required>
                        {%if record.change_type%}
                              <option value="{{record.change_type}}" selected>  {{record.change_type}} </option>
                        {%endif%}
                        <option value="تغيير سلاح "> تغيير سلاح </option>
                        <option value="تسجيل بيانات 34">تسجيل بيانات 34</option>
                        <option value=" فك بصمة"> فك بصمة</option>
                        <option value="تغير الحالة">تغير الحالة</option>
                        <option value="تسجيل بيانات عدم اللياقة الطبية">تسجيل بيانات عدم اللياقة الطبية</option>
                        <option value=" اعادة طباعة 1 س "> اعادة طباعة 1 س</option>
                        <option value=" تعديل ميعاد اللجنة العليا"> تعديل ميعاد اللجنة العليا</option>
                        <option value=" اعادة طباعة كارت الفحص الطبى"> اعادة طباعة كارت الفحص الطبى</option>
                        <option value=" اعادة طباعة كارت الترحيل"> اعادة طباعة كارت الترحيل</option>
                        <option value=" الغاء حضور شاب"> الغاء حضور شاب</option>
                        <option value=" الغاء ترحيل شاب"> الغاء ترحيل شاب</option>
                        <option value=" اعادة طباعة 110 جند"> اعادة طباعة 110 جند</option>
                        <option value=" تعديل بيانات اساسية 34"> تعديل بيانات اساسية 34</option>
                        <option value=" اعادة تصوير"> اعادة تصوير</option>
                        <option value=" تعديل الاسم الاول"> تعديل الاسم الاول</option>
                        <option value=" استبعاد طلبية"> استبعاد طلبية</option>
                        <option value=" تعديل تاريخ الميلاد"> تعديل تاريخ الميلاد</option>
                        <option value=" تعديل المعاملة التجنيدية"> تعديل المعاملة التجنيدية</option>
                        <option value=" تصديق اسم مستخدم"> تصديق اسم مستخدم</option>

                        </select>
      </div>






            </div>

        <!-- form div-->
        <div class="row form-group " style ="margin-right:40%">
          <input type="submit"  class="btn btn-sm btn-primary m-2" name="submit" value="حفظ التعديل">

          <a  class="btn btn-sm btn-danger m-2" href="{% url 'archef:store'  %}">رجوع</a>

          {% if success %}
            <p class="text-danger  m-2 " style="font-size:1.5em;"> تم التعديل بنجاح</p>
          {%endif%}

        </div>
        </div>

    </form>

  </div>



{% endblock %}

archef_n_2/archef/templates/archef/edit_d.html
<!DOCTYPE html>
{% extends "archef/base.html" %}
{% load static %}
<script src="{% static 'archef/store.js' %}"></script>


{% block body_block %}

  <div class="container jumbotron " style="direction:rtl">

    <!-- form model -->
    <form method="post"  target="_self" enctype="multipart/form-data">
    {%csrf_token%}
        <div class="form-group">

            <div class="row">
                <label for="name" class="col-sm-2 bg-light  disabled text-center m-1" > رقم القرار </label>
                <input  id ="name" name="decision_num" type='number'  value="{{decision.dec_num}}" class='col-sm-3  form-control-lg ml-4 '  required >


                <label for="year" class="col-sm-2 btn-md bg-light  disabled text-center m-1" >لسنة  </label>
                <input  id ="year"  name ="decision_year" type='number' class='col-sm-3  form-control-lg  ml-4' pattern="[0-9]{4}"  value="{{decision.dec_year}}"  >

            </div>


            <div class="row mr-2 form-group mt-2">

                <label for="name" class="col-sm-3 bg-light  disabled text-center m-2" > تاريخ القرار </label>
                <label for="year" class="col-sm-3 btn-md bg-light  disabled text-center m-2  " >الفرع المختص  </label>

            </div>


            <div class="row mr-2 form-group ">
                    <input  id ="name" type='date'  name= "decision_date"class='col-sm-3 form-control-lg ml-4 '  >

                    <!-- THis Will be a list for now after that it will be a text choosen manullay depend on user type -->
                    <!-- <input  id ="year" type='text' class='col-sm-3 form-control-lg  ml-4'  value=""  >-->

                    <div class="col-sm-3 form-control-lg  ml-4">
                        <select class="form-control" name="part">
                        <option value="{{decision.related_part}}" selected>{{decision.related_part}}</option>
                        <option value="الصالة">الصالة</option>
                        <option  value="المجمع" >المجمع</option>
                        <option value="الانتقاء والتوجيه">الانتقاء</option>
                        <option value="المعسكر">المعسكر</option>
                        <option value=" قومسيون الطبى"> القومسيون الطبى</option>
                        <option value=" الأمن "> الأمن</option>
                        <option value=" القضاء"> القضاء</option>
                        </select>
                      </div>

                   <label for="url" class="col-sm-2 btn-md bg-light  disabled text-center  " >صورة القرار</label>
                    <input type="file" placeholder="نسخة القرار" class=" btn-md  col-sm-2" id="url" name="url" > 




            </div>
            <div class="row mr-2 form-group ">
                <input  id ="name" type='text' class='col-sm-3  form-control-lg ml-4'  value="{{decision.dec_date}}" readonly >
                <a  align="center"  class="form-control col-sm-3  btn-info btn-lg m-1" target="_blank" href="{{ decision.decision_file.url }}"> معاينة صورة القرار </a>
            </div>
        <!-- form div-->
        </div>

        <div class="row form-group " style ="margin-right:40%">
          <input type="submit"  class="btn btn-sm btn-primary m-2" name="submit" value="حفظ التعديل">

          <a  class="btn btn-sm btn-danger m-2" href="{% url 'archef:store'  %}">رجوع</a>

          {% if success %}
            <p class="text-danger  m-2 " style="font-size:1.5em;"> تم التعديل بنجاح</p>
          {%endif%}

        </div>


    </form>

  </div>



{% endblock %}

archef_n_2/archef/templates/archef/index.html
<!-- Just a test page  dummy code -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>
<body >
    <form method='post'> 
    {% csrf_token %}
        <input  type='text' name='user_name' required><br>
        <input  type='password' name='user_password' required><br>
        <input type='submit' value='submit'>
    </form>
    
</body>
</html>

archef_n_2/archef/templates/archef/start_page.html
<!DOCTYPE html>
{% extends "archef/base.html" %}
{% load static %}



{% block body_block %}
          <!--  adjust window height and size on login -->
          
    
        <div class="jumbotron" >

                
                 <div class="row">
                    <a class=" m-2 btn-lg  btn-block   bg-light  disabled text-center font-weight-bold active" href="{% url 'archef:store' %}">تســجـيل قـرارت السيد مــدير المنطقة </a>
                </div>

                 <div class="row">
                    <a  class="m-2 btn-lg  btn-block   bg-light  disabled text-center font-weight-bold active" href="{% url 'archef:search' %}">الإستعلام عن التعديلات بالثلاثــى</a>
                </div>
        
                
                
           
       
    </div><!-- /container -->

    


{% endblock %}

archef_n_2/archef/templates/archef/view.html
<!DOCTYPE html>
{% extends "archef/base.html" %}
{% load static %}



{% block body_block %}
        {% if record %}
          <!--  adjust window height and size on login -->
            <div style="direction:rtl" >

                 <div class="row">
                    <h3 class=" m-2 btn-lg  btn-block   bg-light  disabled text-center font-weight-bold" > الإستعلام عن التعديلات بالثلاثــى</h3>
                </div>
                <div class="row ml-auto" >
                     <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold" > السنة </h3>
                     <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold" > المركز </h3>
                     <h3 class=" col-2 m-1 btn-lg  bg-light  disabled text-center font-weight-bold " > المسلسل</h3>
                     <a href="{%  url 'archef:search'%}"> <input type="submit"  value ="بحث جديد"  class="  m-1 btn-lg  bg-light  disabled text-center font-weight-bold" ></a>
                     <a href="{%  url 'archef:store'%}"> <input type="submit"  value =" تسجيل قرارت"  class="  m-1 btn-lg  bg-light  disabled text-center font-weight-bold" ></a>

                </div>


                <div class="row ml-auto form-group" >
                    <input type='text' class='col-2 from-control m-1 text-right'  name='year' value = "{{record.year}}" readonly >
                    <input type='text' class='col-2 from-control m-1 text-right' name='markaz' value = "{{record.markaz}}" readonly >
                    <input type='text' class='col-2 from-control m-1 text-right'  name='mosalsal' value = "{{record.mosalsal}}" readonly>


                </div>

            </div>

            <!-- display result of searc here -->

            <div style="direction:rtl" >


                    <div class="row ml-auto form-group mt-4">
                         <label for="name" class="col-sm-2 bg-light  disabled text-center m-1" > الاسم </label>
                        <input type='text' class='col-sm-6  form-control ' value = "{{record.name}}" readonly >


                    </div>
                     <div class="row ml-auto form-group mt-4">
                         <label for="name" class="col-sm-2 bg-light  disabled text-center m-1" >الرقم القومى</label>
                        <input type='number' class='col-sm-6  form-control ' value = "{{record.nat_id}}" readonly >


                    </div>


            </div>

             <p class="text-right  " style="color: black; font-size:2em;"> التعديلات</p>


            <div  >
                <table class='table mt-4 table-striped' style="direction:rtl">


                <head >
                <tr class=" text-right bg-light table-hover" >
                    <td  scope="col">رقم القرار</td>
                    <td  scope="col">لسنة </td>
                    <td  scope="col">تاريخ القرار</td>
                    <td  scope="col">الفرع المختص</td>
                    <td  scope="col">نوع التعديل</td>
                    <td  scope="col"> معاينة صورة القرار </td>
                </tr>
                </thead>

                <tbody>
                <!-- for loop here over decision fields -->
                  {% for record in records %}
                    <tr class=" text-right  "  style="background-color: black; color:white;">
                    <td  scope="col"> {{record.decision.dec_num}}</td>
                    <td  scope="col">{{record.decision.dec_year}} </td>
                    <td  scope="col">{{record.decision.dec_date}}</td>
                    <td  scope="col">{{record.decision.related_part}}</td>
                    <td  scope="col"> {{record.change_type}}</td>
                     <!-- this will be a pop up form or modal to add new records to the decision -->
                    {% if  record.decision.decision_file %}
                    <td scope="col" >
                         <a    target="_blank" href="{{ record.decision.decision_file.url }}">صورة القرار</a>
                    </td>
                    {% else %}
                    <td  scope="col">  مسار الصورة على جهاز 33 :  {{record.decision.dec_num}}\{{record.decision.dec_year}}</td>
                    {% endif %}
                    </tr>
                    {% endfor %}
                    <!-- <tr class=" text-right  "  style="background-color: black; color:white;">
                    <td  scope="col"> 1</td>
                    <td  scope="col">34 </td>
                    <td  scope="col">24/8/2020 </td>
                    <td  scope="col">مجمع خدمات المواطنين </td>
                    <td  scope="col"> بيانات أساسية 34</td>
                    </tr>
                    <tr class=" text-right  "  style="background-color: black; color:white;">
                    <td  scope="col"> 1</td>
                    <td  scope="col">34 </td>
                    <td  scope="col">24/8/2020 </td>
                    <td  scope="col">مجمع خدمات المواطنين </td>
                    <td  scope="col"> بيانات أساسية 34</td>
                    </tr> -->

                </tbody>

                </table>



            </div>

            {% else %}
             <div  style="direction: rtl;" class="jumbotron">
                <h2 class="text-center font-weight-bold ">  لا توجد اية بيانات   لهذا الثلاثى فى قاعدة البيانات برجاء التاكد من الرقم الثلاثى <h2> <br>
                <a href="{%  url 'archef:search'%}"> <input type="submit"  value ="بحث جديد"  class="  m-1 btn-lg  bg-light  disabled text-center font-weight-bold" ></a>
                <a href="{%  url 'archef:store'%}"> <input type="submit"  value =" تسجيل قرارت"  class="  m-1 btn-lg  bg-light  disabled text-center font-weight-bold" ></a>

            </div>
            {% endif %}









{% endblock %}